name: Sync metrics to profile

on:
  workflow_run:
    workflows: ["Metrics"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v3

      - name: Download metrics.svg
        run: |
          mkdir -p sync
          cp metrics.svg sync/metrics.svg

      - name: Checkout profile repo (LerronF)
        uses: actions/checkout@v3
        with:
          repository: LerronF/LerronF
          token: ${{ secrets.LERRONF_TOKEN }}
          path: profile-repo

      - name: Copy file to profile repo
        run: |
          cp sync/metrics.svg profile-repo/metrics.svg

      - name: Commit and push to profile repo
        run: |
          cd profile-repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add metrics.svg
          git commit -m "sync: atualiza metrics.svg automático 🔄" || echo "Nada novo para commitar"
          git push
